### ISSUE TITLE
V1 Bug: Seg Fault when right clicking display on Woldermar

### ISSUE THREAD

**Issue by Coirt** [lindenbergresearch/LRTRack#48]
Right clicking on the display will crash rack

```
[3.166 info src/main.cpp:161] Starting engine
[New Thread 9036.0x5e4]
[3.166 info src/main.cpp:173] Running window
[New Thread 9036.0x774]
[New Thread 9036.0x17e4]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000007764b6 in rack::app::ParamLabel::step (this=0x1d3d20d0)
    at src/app/ParamWidget.cpp:82
82                      text = paramWidget->paramQuantity->getString();
(gdb) bt
#0  0x00000000007764b6 in rack::app::ParamLabel::step (this=0x1d3d20d0)
    at src/app/ParamWidget.cpp:82
#1  0x00000000004a3887 in rack::widget::Widget::step (
    this=this@entry=0x1fd10e10) at src/widget/Widget.cpp:151
#2  0x000000000049edd3 in rack::ui::Menu::step (this=0x1fd10e10)
    at src/ui/Menu.cpp:29
#3  0x00000000004a3887 in rack::widget::Widget::step (this=0x1d3d1ef0)
    at src/widget/Widget.cpp:151
#4  0x00000000004a3887 in rack::widget::Widget::step (this=0x6ae9cb0)
    at src/widget/Widget.cpp:151
#5  0x000000000048c8c9 in rack::app::Scene::step (this=0x6ae9cb0)
    at src/app/Scene.cpp:49
#6  0x0000000000453441 in rack::Window::run (this=0x6ae2b70)
    at src/window.cpp:365
#7  0x000000000079b849 in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.cpp:174
(gdb)
```

**Comment by lindenbergresearch** [comment]
Have been fixed in current v1.0.0 branch... thanks for reporting! :-)

**Comment by Coirt** [comment]
@lindenbergresearch no problem out of curiosity what was causing the problem?

**Comment by lindenbergresearch** [comment]
On Vampyr the right click event is caught and processed, because it has different modes, but on Woldemar it is just a display which resulted in accessing a unbound object (nullptr).

**Comment by Coirt** [comment]
Interesting :+1:
