### ISSUE TITLE
Westcoast crashes Rack when connected to input

### ISSUE THREAD

**Issue by Coirt** [lindenbergresearch/LRTRack#53]
I think I have used Westcoast and not had this crash. I was talking part in a collaboration patch in [this thread](https://community.vcvrack.com/t/anyone-interested-in-playing-musical-pals/5056/32?u=coirt) on the community forum when I got a crash after another**user added modules to the [patch](https://community.vcvrack.com/t/anyone-interested-in-playing-musical-pals/5056/36?u=coirt) which then started crashing rack for me but not him or anyone else in the disccussion/collab.

Connecting to the input of Westcoast is causing a segmentation fault:
_Latest rack release and dev commit f4151bed2ece0fa1eee79fe15c4ec1af883c590e
Windows 7
**Windows 10_
```
Thread 12 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 5692.0x215c]
Westcoast::process (this=0x1032df40, args=...)
    at src/modules/Westcoast.cpp:168
168         reflect->gainBtn->setIndicatorActive(inputs[CV_GAIN_INPUT].isConnected());
(gdb) bt
#0  Westcoast::process (this=0x1032df40, args=...)
    at src/modules/Westcoast.cpp:168
#1  0x000000000049a079 in rack::engine::Engine_stepModules (threadId=0,
    that=<optimized out>) at src/engine/Engine.cpp:258
#2  0x000000000049c527 in rack::engine::Engine_step (that=0x6650b10)
    at src/engine/Engine.cpp:335
#3  rack::engine::Engine_run (that=0x6650b10) at src/engine/Engine.cpp:432
#4  rack::engine::Engine::<lambda()>::operator() (__closure=<optimized out>)
    at src/engine/Engine.cpp:461
#5  std::__invoke_impl<void, rack::engine::Engine::start()::<lambda()> > (
    __f=...) at C:/msys64/mingw64/include/c++/8.2.1/bits/invoke.h:60
#6  std::__invoke<rack::engine::Engine::start()::<lambda()> > (__fn=...)
    at C:/msys64/mingw64/include/c++/8.2.1/bits/invoke.h:95
#7  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/8.2.1/thread:244
#8  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::operator() (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/8.2.1/thread:253
#9  std::thread::_State_impl<std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/8.2.1/thread:196
#10 0x000000006fd0891f in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#11 0x0000000064944b90 in ?? () from C:\msys64\mingw64\bin\libwinpthread-1.dll
#12 0x000007fefe62415f in srand () from C:\Windows\system32\msvcrt.dll
#13 0x000007fefe626ebd in msvcrt!_ftime64_s ()
   from C:\Windows\system32\msvcrt.dll
#14 0x00000000773859cd in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\system32\kernel32.dll
#15 0x00000000775e385d in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#16 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

It was a though crash to find had to manually remove cables from the save to narrow down :disappointed:

**Comment by lindenbergresearch** [comment]
Fixed
